import React from "react";
import { AbsoluteFill, Audio, OffthreadVideo, Sequence, interpolate, staticFile, useCurrentFrame, useVideoConfig } from "remotion";

type Shot={id:string;source_filename:string;start:number;end:number;speed?:number;speed_curve?:Array<{at?:number;speed?:number}>;zoom_start?:number;zoom_end?:number;motion?:string;transition_in?:string;transition_out?:string;crop?:string;source_audio_volume?:number;on_screen_text?:string;text_position?:string;text_style?:string;text_animation?:string;text_size?:number;text_color?:string;text_weight?:number;emphasis_words?:string[];brightness?:number;contrast?:number;saturation?:number;blur?:number;x?:number;y?:number;rotation?:number;color_treatment?:string};
type Sfx={source?:string;start?:number;duration?:number;volume?:number;fadeIn?:number;fadeOut?:number};
type Props={shots:Shot[];assets:Record<string,string>;voice?:string;music?:string;musicVolume?:number;musicDucking?:boolean;musicDuckingDb?:number;sfx?:Sfx[];fps:number;width:number;height:number};
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const curve=(c:any[]|undefined,p:number,f:number)=>{if(!Array.isArray(c)||c.length<2)return f;const a=c.map(x=>({at:clamp(Number(x.at)||0,0,1),v:clamp(Number(x.speed)||f,.5,3)})).sort((x,y)=>x.at-y.at);for(let i=1;i<a.length;i++)if(p<=a[i].at){const q=(p-a[i-1].at)/Math.max(.0001,a[i].at-a[i-1].at);return a[i-1].v+(a[i].v-a[i-1].v)*q}return a[a.length-1].v};
const pos=(c?:string)=>{const x=String(c||"CENTER").toUpperCase();return ({FACE:"50% 38%",PRODUCT:"50% 52%",ACTION:"50% 55%",LEFT:"30% 50%",RIGHT:"70% 50%",TOP:"50% 30%",BOTTOM:"50% 70%"} as any)[x]||"50% 50%"};
const textPos=(p?:string)=>String(p||"BOTTOM").toLowerCase().includes("top")?{top:130}:{bottom:180};
const transition=(v?:string)=>{const x=String(v||"CUT").toUpperCase();return x==="MATCH"?"CROSSFADE":x};
const ShotLayer=({shot,src,duration,index}:{shot:Shot;src:string;duration:number;index:number})=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=clamp(frame/Math.max(1,duration-1),0,1);const speed=curve(shot.speed_curve,p,Number(shot.speed)||1);const tin=transition(shot.transition_in);const tout=transition(shot.transition_out);const edge=Math.min(15,Math.max(5,Math.round(duration*.12)));const ep=clamp(frame/edge,0,1);const xp=clamp((duration-1-frame)/edge,0,1);const e=ep*ep*(3-2*ep);const xep=xp*xp*(3-2*xp);let opacity=1,tx=0,ty=0,scale=interpolate(p,[0,1],[Number(shot.zoom_start)||1,Number(shot.zoom_end)||1.04]);
if(tin==="DISSOLVE"||tin==="FADE"||tin==="CROSSFADE")opacity=e;if(tout==="DISSOLVE"||tout==="FADE"||tout==="CROSSFADE")opacity*=xep;if(tin==="SLIDE_LEFT")tx=interpolate(e,[0,1],[-100,0]);if(tin==="SLIDE_RIGHT")tx=interpolate(e,[0,1],[100,0]);if(tin==="SLIDE_UP")ty=interpolate(e,[0,1],[100,0]);if(tin==="SLIDE_DOWN")ty=interpolate(e,[0,1],[-100,0]);if(tin==="ZOOM"||tin==="PUNCH")scale*=interpolate(e,[0,.7,1],[1.12,1.025,1]);if(tin==="WHIP"){tx=interpolate(e,[0,1],[index%2?-120:120,0]);scale*=interpolate(e,[0,1],[1.04,1])}
const motion=String(shot.motion||"STATIC").toUpperCase();let mx=0,my=0,rot=Number(shot.rotation)||0;if(motion==="PAN_LEFT")mx=interpolate(p,[0,1],[1.8,-1.8]);else if(motion==="PAN_RIGHT")mx=interpolate(p,[0,1],[-1.8,1.8]);else if(motion==="DRIFT"){mx=interpolate(p,[0,1],[-1.2,1.2]);my=interpolate(p,[0,1],[.7,-.7])}else if(motion==="TILT_UP")my=interpolate(p,[0,1],[1.5,-1.5]);else if(motion==="TILT_DOWN")my=interpolate(p,[0,1],[-1.5,1.5]);else if(motion==="HANDHELD"){mx=Math.sin(frame*.19+index*17)*.4;my=Math.cos(frame*.23+index*17)*.3;rot+=Math.sin(frame*.11+index)*.15}const preset=String(shot.color_treatment||"CLEAN_PREMIUM").toUpperCase();const filters=`brightness(${Number(shot.brightness)||1.02}) contrast(${Number(shot.contrast)||1.1}) saturate(${Number(shot.saturation)||1.02})${Number(shot.blur)?` blur(${Number(shot.blur)}px)`:""}`;
return <AbsoluteFill style={{opacity,overflow:"hidden",transform:`translate(${tx+mx+Number(shot.x||0)}%,${ty+my+Number(shot.y||0)}%) rotate(${rot}deg) scale(${scale})`,transformOrigin:pos(shot.crop),filter:filters}}><OffthreadVideo src={staticFile(src)} startFrom={Math.round(shot.start*fps)} endAt={Math.round(shot.end*fps)} playbackRate={speed} muted={Number(shot.source_audio_volume||0)<=0} style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:pos(shot.crop)}}/><TextLayer shot={shot} duration={duration}/></AbsoluteFill>};
const TextLayer=({shot,duration}:{shot:Shot;duration:number})=>{const f=useCurrentFrame();const t=String(shot.on_screen_text||"").trim();if(!t)return null;const n=Math.min(12,Math.max(5,Math.round(duration*.12)));const enter=clamp(f/n,0,1),out=clamp((duration-f)/n,0,1);const a=enter*enter*(3-2*enter)*out;const anim=String(shot.text_animation||"FADE").toUpperCase();const y=anim.includes("UP")?interpolate(enter,[0,1],[30,0]):0;return <div style={{position:"absolute",left:55,right:55,...textPos(shot.text_position),opacity:a,transform:`translateY(${y}px)`,fontSize:Number(shot.text_size)||76,fontWeight:Number(shot.text_weight)||800,color:shot.text_color||"white",fontFamily:"Arial, sans-serif",lineHeight:1.05,textAlign:"center",textShadow:"0 4px 18px rgba(0,0,0,.45)",letterSpacing:-1}}>{t}</div>};
export const AtlasProEditV2:React.FC<Props>=({shots,assets,voice,music,musicVolume=.12,musicDucking=true,sfx=[]})=>{const {fps}=useVideoConfig();let cursor=0;return <AbsoluteFill style={{background:"black"}}>{shots.map((shot,i)=>{const dur=Math.max(8,Math.round((shot.end-shot.start)/Math.max(.5,Number(shot.speed)||1)*fps));const next=shots[i+1];const tr=String(next?.transition_in||"CUT").toUpperCase();const overlap=["DISSOLVE","FADE","CROSSFADE","MATCH","WHIP","SLIDE_LEFT","SLIDE_RIGHT","SLIDE_UP","SLIDE_DOWN","ZOOM","PUNCH"].includes(tr)?Math.min(Math.round(.28*fps),Math.floor(dur*.18)):0;const from=Math.max(0,cursor-overlap);const shown=dur+overlap;const src=assets[shot.source_filename]||"";const node=<Sequence key={shot.id} from={from} durationInFrames={shown}><ShotLayer shot={shot} src={src} duration={dur} index={i}/></Sequence>;cursor+=dur-overlap;return node})}{voice&&<Audio src={staticFile(voice)} volume={1}/>} {music&&<Audio src={staticFile(music)} volume={musicVolume}/>} {sfx.map((x,i)=>x.source?<Sequence key={`sfx-${i}`} from={Math.max(0,Math.round(Number(x.start||0)*fps))} durationInFrames={Math.max(1,Math.round(Number(x.duration||.8)*fps))}><Audio src={staticFile(x.source)} volume={clamp(Number(x.volume)||.15,.02,.5)}/></Sequence>:null)}</AbsoluteFill>};